### ISSUE TITLE
Using the `route/not-found` with a custom status code?

### ISSUE THREAD

**Issue by stonetwig** [weavejester/compojure#143]
```
(defroutes app
  "This is the function we pass to Ring. It will be called with a
   request map for every request."
  (GET "/client-type-endpoints" [] (render-file "templates/client-type-endpoints.html" {:somedata "data"}))
  (route/resources "/")
  (route/not-found (-> get-pages
      (stasis/serve-pages)
      wrap-exceptions
      (optimus/wrap get-assets optimize
                    (if freeze-assets? serve-frozen-assets serve-live-assets))
                    )))
```

This is a snippet from my current code. We are using some other libraries to serve static markdown pages. However I was in a need for some specific routes and thought it was easy to simply throw in compojure in front of the other code.

Altough, since there already exist some routing I simply wanted to "shuffle" all requests to the other library if I had no custom route that was not a static site. I used the `not-found` but noticed it sends a 404 status code with each page request.

An image:
![](https://s3.amazonaws.com/f.cl.ly/items/3f2F123k0P2p223p0e3R/Image%202015-09-03%20at%208.51.18%20am.png)

As you can see, the compiled static files all gets 404 even the initial request even if it renders the correct html. 

But if I do a request to the resource requested by the browser, it renders perfectly well:
![](https://s3.amazonaws.com/f.cl.ly/items/0r2C1t2k0N1X0X1a0O1p/Image%202015-09-03%20at%208.53.03%20am.png)

My question is if you know a simple way to keep all existing  code and how to add a new route that can render a specific page but still keep the custom routing engine? Simply put, I need a `not-found` function that does not send a 404.

Can this be done with compojure? I am really, really new at clojure so please explain it in a simple way!

**Comment by weavejester** [comment]
Compojure is based on two principles:

1. Routes are Ring handler functions that may return nil
2. Routes are tried in order until one returns a non-nil value

All Ring handlers are Compojure routes, so you can take a Ring handler like `stasis/serve-pages` and use it as a route.

For example:

```clojure
(def app-routes
  (routes
   (GET "/client-type-endpoints" [] (render-type-endpoints))
   (route/resources "/")
   (stasis/serve-pages get-pages)))
```

Each argument passed to `routes` is a function that may return a response, or `nil`. The `routes` function tries each of its arguments in order, until it finds one that succeeds.

You should now see that there's no need for a "a `not-found` function that does not send a 404", because any handler function can be inserted directly into the routes.

Note that the `defroutes` macro is just shorthand for `def` and `routes`

**Comment by stonetwig** [comment]
Thank you so much for that awesome answer, it really helped me and I solved the issue as per your example. Clojure can be hard for a programmer not used to it, but the community as awesome as you makes things easier.
