### ISSUE TITLE
I need to upload file. How?

### ISSUE THREAD

**Issue by salmazov** [weavejester/compojure#144]
```clojure
(ns ringtest
	(:require
		[compojure.core :refer [defroutes GET POST]]
		[noir.io :as io]
		[ring.adapter.jetty :as jetty]
		[ring.middleware.params :refer [wrap-params]]))

(def myform 
	(str "<html>"
			"<body>"
				"<form action='/upload' method='post' enctype='multipart/form-data'>"
					"<input type='file' name='filename'>"
					"<input type='submit' value='Hello!'>"
				"</form>"
			"</body>"
		"</html>"))

(defn show-form []
	{:body myform
	 :status 200})

(defroutes mainroutes
	(GET "/" [] (show-form))
	(POST "/upload" [file] 
	 (io/upload-file "/tmp/" file)
	 )

(defn -main [& args]
  (jetty/run-jetty mainroutes {:port 3001}))
```

doesn't work for me

**Comment by weavejester** [comment]
Please only raise an issue if there is an issue with Compojure itself. For questions, please using the [Google Group](https://groups.google.com/forum/#!forum/compojure) instead.

However, your problem is simply that you haven't added the [multipart middleware](https://ring-clojure.github.io/ring/ring.middleware.multipart-params.html) to your application, or indeed *any* middleware of any sort. Without middleware, Ring supports only the bare bones of HTTP (no sessions, cookies, parameters or anything like that).
