### ISSUE TITLE
Why does the exception stacktrace disappear if I refresh the page?

### ISSUE THREAD

**Issue by ilja903** [weavejester/compojure#149]
When I make some typo in the code (for instance, I have forgotten to add ')' to the end of sth) then I see a stacktrace in the browser which is totally fine. However , if I refresh the page, then the exception suddenly disappears. Is there any flag, which could prevent compojure (or ring?) from doing this? Seems like a really undesired behavior for me.

**Comment by weavejester** [comment]
Compojure is just a routing library. Your issue is with `ring.middleware.reload` namespace (or potentially another similar tool that handles reloading).

The reload middleware will only reload files that have changed. If the file has a syntax error, then when it loads the file it fails to compile and an exception is thrown. However, because it has not been compiled, the loaded namespace in memory remains the same, and because the file has not changed, the reload middleware will not attempt to load it again. This is why the reload middleware does not generate an error message more than once.

There's a pull request https://github.com/ring-clojure/ring/pull/214 around this, but it has some issues with it, so it hasn't been merged. This functionality might show up in Ring 1.5.0 as an optional flag.
