### ISSUE TITLE
Parameter coercion of booleans

### ISSUE THREAD

**Issue by khadiwala** [weavejester/compojure#150]
I have a route like this
```clojure
(defroutes app-routes
  (GET "/foo/:bar" [bar :<< Boolean/valueOf] "success"))
```
where I'm trying to coerce bar to a boolean. `/foo/true` is matched by this route, but `/foo/false` is not. What I'm guessing is happening is that because my coercion function is returning false, it is assumed to have failed. If I have that right, I think this is incorrect and only nil should be considered a failed match as indicated in the documentation here: https://github.com/weavejester/compojure/wiki/Destructuring-Syntax#parameter-coercion.

**Comment by weavejester** [comment]
Thanks for the report! I believe that's a bug. The problem is in on [line 114 of core.clj](https://github.com/weavejester/compojure/blob/master/src/compojure/core.clj#L114), where `and` was used, instead of checking to see whether all the values were `nil`.

As an aside, however, `Boolean/valueOf` isn't a function, and so currently only works by happenstance. In Clojure static methods can't be treated the same as functions, because they're not objects.
