### ISSUE TITLE
Record route meta data on a handler to list all defined routes

### ISSUE THREAD

**Issue by johnmcconnell** [weavejester/compojure#160]
This is useful for testings and middleware.

For example.
```clojure
(defroutes app
  (GET "/h1" ...)
  (GET "h1" ...)
  ...)
```

```clojure
(route-list app)
[[:GET "/h1"] [:GET "h2"] ... ]
```

```clojure
(meta app)
{:route-list [[:GET "h1"] [:GET "h2"] ... ]
```

**Comment by weavejester** [comment]
The problem with this is that it's impossible to do reliably, because routes can contain other routes. I don't like the idea of introducing a feature that works sometimes, but not other times.

**Comment by johnmcconnell** [comment]
Can a route be expanded by concatenating the path?

Or can we change the route list to a route tree?

**Comment by weavejester** [comment]
Routes are Turing-complete, so there's no way of producing a *reliable* routing tree from a set of Compojure routes.

I have been working on [Ataraxy](https://github.com/weavejester/ataraxy), a data-driven syntax for routing, and I should get back to developing that soon because I intend to use it in [Duct](https://github.com/duct-framework/duct). There are also other data-driven routing syntaxes around like [Bidi](https://github.com/juxt/bidi).

Unfortunately Compojure's core design prevents it from being transformed into a tree of routes. Compojure is powerful, but power creates opacity.

**Comment by johnmcconnell** [comment]
Ahh... so are the routes like "crawled" at runtime then?

**Comment by johnmcconnell** [comment]
I'll take a look. Thanks!

**Comment by weavejester** [comment]
Each route is a function that returns either a response or `nil`, if the route doesn't match. You can therefore have routes that are just functions that can respond to very complex conditions.

**Comment by johnmcconnell** [comment]
How about only supporting this feature only for handlers defined using `defroutes`?

I can implement it

**Comment by weavejester** [comment]
I'm afraid I don't want a feature in Compojure that only works only sometimes, under specific conditions. I'd rather things either work or not.

**Comment by jiacai2050** [comment]
I don't think that this is a practical feature for Compojure just as @weavejester said.

If `list all available routes` is necessary, I think [bidi](https://github.com/juxt/bidi#route-sequences) is more suitable.

**Comment by johnmcconnell** [comment]
Cool. I'm looking to get this integrated with compojure-api because of the auto generated swagger ui. I'll see if this feature is a better fit for that project. Thanks guys.
