### ISSUE TITLE
Maximum (50) redirects followed 

### ISSUE THREAD

**Issue by rmGFW** [weavejester/compojure#220]
lein ring server-headless works well , when i request to http://host/, it redirect to http://host/index.html, but when i deploy it use uberjar ,and curl http://host/,  Maximum (50) redirects followed, i already put reousrce in the same folder with jar and that also the working directory
```clojure
(defroutes app-routes
  (context "/api" [] api-routes)
  (route/resources "resources/public")
  (GET "*" [] (redirect "/index.html"))
  (route/not-found "Not Found")
)
```

**Comment by weavejester** [comment]
You've likely set your resources wrong. The `compojure.route/resources` function takes a classpath prefix, rather than a directory path. 

By default, Leiningen adds the `resources` directory to the classpath, so if you want to search for resources in `resources/public`, you'd omit the beginning `resources`. In other words, you want:

```clojure
(defroutes app-routes
  (context "/api" [] api-routes)
  (route/resources "public")
  (GET "*" [] (redirect "/index.html"))
  (route/not-found "Not Found"))
```

The next problem you have is that redirect. That's what was causing the "maximum redirects" error. Because you put in the wrong resource path, it couldn't find `index.html`, and so was stuck in an infinite loop. However, even with this fixed you still have the problem that any invalid path will redirect to `/index.html` because you're using a catch-all `*` route.

You likely want:

```clojure
(defroutes app-routes
  (context "/api" [] api-routes)
  (route/resources "public")
  (GET "/" [] (redirect "/index.html"))
  (route/not-found "Not Found"))
```

**Comment by rmGFW** [comment]
thanks , and another question , do i need use `lein ring uberwar` to generate the war file rather than jar (use command `lein uberjar`)

**Comment by rmGFW** [comment]
i use lein uberjar to generate the jar file and set CLASSPATH env to /app:/app/resources/:xxx.jar, and put reousres/public in the /app , and use `java -jar xxx.jar` start the server , but it still can't find my resource . i curl localhost:3000/index.html , it return not found

**Comment by weavejester** [comment]
War files are used by Java web servers (Servlet Containers). Jars are used if you want a standalone application.

Without knowing more information I can't discern what's wrong with your application. However, it may help if you understand how Leiningen works. By default, Leiningen adds three paths to the classpath:

- `resources`
- `src`
- `test`

The last one, `test`, is used only for testing. The others are added to a jar or uberjar.

The difference between a jar and an uberjar is that an uberjar also includes all additional dependencies. This makes an uberjar entirely self-contained.

Suppose you have a directory tree like:

- `resources`
  - `public`
    - `index.html`
- `src`
  - `example`
    - `app.clj`

When Leiningen compiles a jar (which is just a fancy zip file), it creates a structure in the jar like:

- `META-INF`
  - `MANIFEST.MF`
- `public`
  - `index.html`
- `example`
  - `app.clj` 

Notice how the `resources` and `src` directories are merged together. You can take a look inside your jar file with `jar -tf`.
